# Generated by Django 5.1.4 on 2025-01-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0002_blogpost_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_bio',
            field=models.TextField(default=''),
        ),
    ]
