# Generated by Django 5.1.4 on 2025-01-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0003_blogpost_author_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
